use super::*;

mod codec_bank_0104_packet_ids_sizes_and_golden_layout;
mod codec_buddy_lifecycle_0104_packet_ids_and_fixed_re;
mod operations_ep_movement_requests_round_trip_at_the_clean;
mod operations_npc_skill_authority_rejects_malformed_counts;
mod operations_item_use_0104_record_field_offsets_match_cle;
mod operations_guide_npc_transport_0104_payloads_match_clea;
mod operations_nano_skill_success_0104_decodes_every_proven;
mod operations_nano_skill_success_0104_rejects_partial_unkn;
mod commands;
mod input;
mod validation;
mod animation;
mod systems;
mod materials;
mod state;
mod output;

use codec_bank_0104_packet_ids_sizes_and_golden_layout::OPENFUSION_CHAR_SELECT_FRAME;
use operations_ep_movement_requests_round_trip_at_the_clean::{
    append_skill_result_damage, append_skill_result_heal_hp, append_skill_result_buff
};
use output::write_test_i16;
