use super::*;

pub(in super::super) struct TutorialRuntimePlugin;

impl Plugin for TutorialRuntimePlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<TutorialSession>()
            .add_systems(
                Update,
                retain_localized_tutorial_subtitle
                    .before(TutorialVoiceSubtitleSet::Tick)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .init_resource::<TutorialLogicRuntime>()
            .init_resource::<TutorialMissionRuntime>()
            .init_resource::<TutorialAuxiliaryPresentation>()
            .init_resource::<TutorialNativeMechanics>()
            .init_resource::<TutorialActorRegistry>()
            .init_resource::<TutorialActorCommandQueue>()
            .init_resource::<TutorialActorEventQueue>()
            .init_resource::<TutorialActorIssueQueue>()
            .init_resource::<TutorialPlayerPresentationCommandQueue>()
            .init_resource::<TutorialTargetingProfile>()
            .init_resource::<TutorialNpcObservationSnapshot>()
            .init_resource::<TutorialActorCombatConfig>()
            .init_resource::<TutorialActorAnimationAssets>()
            .init_resource::<TutorialActorStandRandomStream>()
            .init_resource::<TutorialAmbientRuntime>()
            .init_resource::<TutorialMissionIndicatorRuntime>()
            .init_resource::<TutorialNanoConditionEffectRuntime>()
            .init_resource::<PendingTutorialActorEffects>()
            .configure_sets(
                Update,
                (
                    TutorialActorSet::ApplyCommands,
                    TutorialActorSet::AdvanceMotion,
                    TutorialActorSet::ProduceTargets,
                    TutorialActorSet::Observe,
                )
                    .chain(),
            )
            .configure_sets(
                Update,
                TutorialActorSet::GroundActors
                    .after(TutorialActorSet::AdvanceMotion)
                    .after(NativeWorldSet::ResolveCollision),
            )
            .configure_sets(
                Update,
                TutorialActorSet::AdvanceCombatAnimation.after(TutorialActorSet::GroundActors),
            )
            .add_systems(
                PreUpdate,
                (
                    sync_tutorial_native_stage,
                    suppress_locked_tutorial_ui_shortcuts,
                )
                    .chain()
                    .after(InputSystems),
            )
            .add_systems(
                OnEnter(ClientState::Tutorial),
                (
                    activate_gameplay_ui,
                    begin_tutorial_effect_library_load,
                    preload_tutorial_effects,
                    start_tutorial_sequence,
                    prime_tutorial_startup_pose,
                )
                    .chain(),
            )
            .add_systems(
                OnExit(ClientState::Tutorial),
                (
                    cleanup_tutorial_actors,
                    cleanup_tutorial_nano_gameplay,
                    cleanup_tutorial_nano_presentation,
                    cleanup_tutorial_ambient,
                    cleanup_tutorial_mission_indicators,
                    cleanup_tutorial_nano_condition_effects,
                    cleanup_pending_tutorial_actor_effects,
                    cleanup_tutorial_effect_runtime_unless_world_ready,
                    cleanup_tutorial_runtime,
                ),
            )
            .add_systems(
                Update,
                apply_tutorial_actor_commands
                    .in_set(TutorialActorSet::ApplyCommands)
                    .before(LegacyAvatarActionSet::Resolve)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .add_systems(
                Update,
                (
                    spawn_tutorial_actor_visuals.before(bind_network_npc_texture_variants_0104),
                    apply_tutorial_actor_animation_playback,
                )
                    .chain()
                    .after(TutorialActorSet::AdvanceCombatAnimation)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .add_systems(
                Update,
                sync_tutorial_world_mission_indicators
                    .after(sync_tutorial_mission_interaction)
                    .before(process_tutorial_effect_runtime)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .add_systems(
                Update,
                sync_tutorial_nano_condition_effects
                    .after(TutorialNanoGameplaySet::ApplyCommands)
                    .after(spawn_tutorial_actor_visuals)
                    .before(process_tutorial_effect_runtime)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .add_systems(
                Update,
                advance_tutorial_actor_combat_animation
                    .in_set(TutorialActorSet::AdvanceCombatAnimation)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .add_systems(
                Update,
                advance_tutorial_actor_motion
                    .in_set(TutorialActorSet::AdvanceMotion)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .add_systems(
                Update,
                ground_tutorial_actors
                    .in_set(TutorialActorSet::GroundActors)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .add_systems(
                Update,
                produce_tutorial_avatar_target_feed
                    .in_set(TutorialActorSet::ProduceTargets)
                    .after(LegacyMovementSet::CameraInput)
                    .before(LegacyAvatarActionSet::Resolve)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .add_systems(
                Update,
                refresh_tutorial_npc_observation
                    .in_set(TutorialActorSet::Observe)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .add_systems(
                Update,
                collect_tutorial_actor_events
                    .after(TutorialActorSet::ApplyCommands)
                    .after(TutorialEffectRuntimeSet::ActorAnimationEvents)
                    .before(process_tutorial_effect_runtime)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .add_systems(
                Update,
                (
                    open_tutorial_exit_dialog_on_shortcut,
                    consume_tutorial_mission_outbox,
                    advance_tutorial_npc_warp.in_set(GameplayAudioSet::Collect),
                    sync_tutorial_mission_interaction,
                    scan_tutorial_location_tasks,
                )
                    .chain()
                    .after(TutorialActorSet::Observe)
                    .after(MissionUiSet::Interaction)
                    .before(process_tutorial_effect_runtime)
                    .before(drive_local_tutorial)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .add_systems(
                Update,
                mission_dialogue::present_tutorial_mission_dialogue
                    .after(drive_local_tutorial)
                    .before(GameplayUiSet::NpcSpeech)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .add_systems(
                Update,
                collect_tutorial_avatar_actions
                    .after(LegacyAvatarActionSet::Resolve)
                    .in_set(GameplayAudioSet::Collect)
                    .before(TutorialNanoGameplaySet::ApplyCommands)
                    .before(LegacyMovementSet::Simulate)
                    .run_if(in_state(ClientState::Tutorial)),
            )
            .add_systems(
                Update,
                collect_tutorial_nano_gameplay_events
                    .after(TutorialNanoGameplaySet::Follow)
                    .before(process_tutorial_effect_runtime)
                    .before(drive_local_tutorial)
                    .run_if(legacy_world_ambience_active),
            )
            .add_systems(
                Update,
                drive_local_tutorial
                    .after(NetworkSessionLifecycleSet::Apply)
                    .after(LegacyMovementSet::CameraPose)
                    .after(TutorialActorSet::Observe)
                    .after(collect_tutorial_actor_events)
                    .after(collect_tutorial_nano_gameplay_events)
                    // Apply the exact SoundUtil.SetPlayer(null/player) edge
                    // before animation-event sounds are distance-gated in the
                    // same frame.
                    .before(GameplayAudioSet::Drive),
            )
            .add_systems(
                Update,
                report_tutorial_runtime_issues
                    .after(NetworkSessionLifecycleSet::Apply)
                    .before(drive_local_tutorial)
                    .run_if(in_state(ClientState::Tutorial)),
            );
    }
}
