
pub const SERVER_SELECTION_REQ_SHARD_LIST_PACKET_ID: u32 = 0x1200_0008;

pub const SERVER_SELECTION_REQ_SHARD_LIST_PACKET_SIZE: usize = 1;

pub const SERVER_SELECTION_REP_SHARD_LIST_PACKET_ID: u32 = 0x2100_0019;

pub const SERVER_SELECTION_REP_SHARD_LIST_PACKET_SIZE: usize = 26;

pub const SERVER_SELECTION_REQ_SERVER_SELECT_PACKET_ID: u32 = 0x1200_000E;

pub const SERVER_SELECTION_REQ_SERVER_SELECT_PACKET_SIZE: usize = 1;
