use super::*;

pub(crate) fn register_network_world_runtime_0104(app: &mut App) {
    transportation::register_network_transportation_visual_runtime_0104(app);
    shiny::register(app);
    app.init_resource::<NetworkNpcVisualCatalogRequest0104>()
        .init_resource::<NetworkNpcVisualCatalogState0104>()
        .init_resource::<NetworkPcVisualDataState0104>()
        .init_resource::<PlayerWeaponAnimationCatalog>()
        .init_resource::<NetworkPcVisualGeneration0104>()
        .init_resource::<NetworkPcAnimationRevision0104>()
        .init_resource::<NetworkHnpcVisualGeneration0104>()
        .init_resource::<NetworkHnpcAnimationRevision0104>()
        .init_resource::<NetworkNpcAnimationAssets0104>()
        .add_systems(
            Update,
            load_network_npc_visual_catalog_0104.after(consume_network_entity_lifecycle_0104),
        )
        .add_systems(
            Update,
            (
                load_network_pc_visual_data_0104,
                resolve_network_hnpc_visuals_0104
                    .after(load_network_npc_visual_catalog_0104)
                    .after(consume_network_entity_lifecycle_0104),
                resolve_network_npc_visuals_0104
                    .after(load_network_npc_visual_catalog_0104)
                    .after(resolve_network_hnpc_visuals_0104)
                    .after(consume_network_entity_lifecycle_0104),
                bind_network_hnpc_attachments_0104.after(resolve_network_hnpc_visuals_0104),
                bind_network_hnpc_materials_0104
                    .after(resolve_network_hnpc_visuals_0104)
                    .after(bind_network_hnpc_attachments_0104),
                finalize_network_hnpc_visuals_0104.after(bind_network_hnpc_materials_0104),
                sync_network_hnpc_animation_0104
                    .after(resolve_network_hnpc_visuals_0104)
                    .after(advance_network_npc_motion_0104),
                bind_network_npc_texture_variants_0104.after(resolve_network_npc_visuals_0104),
                resolve_network_pc_visuals_0104
                    .after(load_network_pc_visual_data_0104)
                    .after(consume_network_entity_lifecycle_0104),
                bind_network_pc_weapon_attachment_0104.after(resolve_network_pc_visuals_0104),
                bind_network_pc_appearance_attachments_0104.after(resolve_network_pc_visuals_0104),
                advance_network_npc_motion_0104.after(consume_network_entity_lifecycle_0104),
                advance_network_transportation_motion_0104
                    .after(consume_network_entity_lifecycle_0104),
                play_network_npc_animation_0104
                    .after(resolve_network_npc_visuals_0104)
                    .after(advance_network_npc_motion_0104),
                apply_network_npc_material_animation_0104
                    .after(play_network_npc_animation_0104)
                    .after(bind_network_npc_texture_variants_0104),
                emit_network_npc_animation_effects_0104
                    .after(play_network_npc_animation_0104)
                    .before(process_tutorial_effect_runtime),
                emit_network_npc_animation_sounds_0104
                    .after(play_network_npc_animation_0104)
                    .in_set(GameplayAudioSet::Collect),
                bind_network_pc_appearance_0104
                    .after(resolve_network_pc_visuals_0104)
                    .after(bind_network_pc_appearance_attachments_0104),
                finalize_network_pc_visuals_0104.after(bind_network_pc_appearance_0104),
                sync_network_pc_animation_0104
                    .after(resolve_network_pc_visuals_0104)
                    .after(consume_network_entity_lifecycle_0104)
                    .after(crate::remote::interpolate_remote_players)
                    .before(crate::player_shared_rig::NativePlayerRigAnimationApply),
            ),
        )
        .add_systems(Update, pc_visibility::animate_pc_visibility.after(finalize_network_pc_visuals_0104))
        .add_systems(Update, sync_network_pc_vehicle_weapon_visibility)
        .add_systems(
            Update,
            emit_network_hnpc_animation_sounds_0104
                .before(sync_network_hnpc_animation_0104)
                .before(crate::player_shared_rig::NativePlayerRigAnimationApply)
                .in_set(GameplayAudioSet::Collect),
        )
        .add_systems(
            Update,
            (
                animate_network_npc_appear_effect_0104
                    .after(bind_network_npc_texture_variants_0104)
                    .run_if(
                        bevy::ecs::schedule::common_conditions::any_with_component::<
                            NetworkNpcAppearEffect0104,
                        >,
                    ),
                finalize_network_npc_material_visibility_0104
                    .after(bind_network_npc_texture_variants_0104)
                    .after(animate_network_npc_appear_effect_0104),
                finish_network_pc_emote_0104.after(sync_network_pc_animation_0104)
                    .after(crate::player_shared_rig::NativePlayerRigAnimationApply),
            ),
        );
}
