use super::*;

pub const EMAIL_UI_SOURCE_BUILD: &str = "retrobution-20260613";

pub const EMAIL_UI_ROOT_INITIALLY_ACTIVE: bool = false;

pub const EMAIL_UI_MAIN_SHA256: &str =
    "59788201962B6A1737B114486C361FE74EEF69F507D1D125CA3171377EEC602F";

pub const EMAIL_UI_TUTORIAL_SHA256: &str =
    "49A684FF4236848D0B882A5D725FFBE99D5CFB5D2090DC8705350E97DD3FD024";

pub const EMAIL_PAGE_SIZE: usize = 5;

pub const EMAIL_PAGE_MAX: i8 = 4;

pub const EMAIL_ATTACHMENT_COUNT: usize = 4;

pub const EMAIL_DELETE_BATCH_COUNT: usize = 5;

pub const EMAIL_BASE_POSTAGE: i32 = 50;

pub const EMAIL_ITEM_POSTAGE: i32 = 20;

pub const EMAIL_SEND_DELAY_SECONDS: u32 = 60;

pub const EMAIL_REQ_PAGE_LIST_ID: u32 = 0x1300_007D;

pub const EMAIL_REQ_DELETE_ID: u32 = 0x1300_007E;

pub const EMAIL_REQ_SEND_ID: u32 = 0x1300_007F;

pub const EMAIL_REQ_RECEIVE_ITEM_ID: u32 = 0x1300_0080;

pub const EMAIL_REQ_RECEIVE_CASH_ID: u32 = 0x1300_0081;

pub const EMAIL_REQ_RECEIVE_ALL_ID: u32 = 0x1300_0089;

pub const EMAIL_REP_NEW_ID: u32 = 0x3100_00E0;

pub const EMAIL_REP_PAGE_LIST_SUCCESS_ID: u32 = 0x3100_00E3;

pub const EMAIL_REP_PAGE_LIST_FAILURE_ID: u32 = 0x3100_00E4;

pub const EMAIL_REP_DELETE_SUCCESS_ID: u32 = 0x3100_00E5;

pub const EMAIL_REP_DELETE_FAILURE_ID: u32 = 0x3100_00E6;

pub const EMAIL_REP_SEND_SUCCESS_ID: u32 = 0x3100_00E7;

pub const EMAIL_REP_SEND_FAILURE_ID: u32 = 0x3100_00E8;

pub const EMAIL_REP_RECEIVE_ITEM_SUCCESS_ID: u32 = 0x3100_00E9;

pub const EMAIL_REP_RECEIVE_ITEM_FAILURE_ID: u32 = 0x3100_00EA;

pub const EMAIL_REP_RECEIVE_CASH_SUCCESS_ID: u32 = 0x3100_00EB;

pub const EMAIL_REP_RECEIVE_CASH_FAILURE_ID: u32 = 0x3100_00EC;

pub const EMAIL_REP_RECEIVE_ALL_SUCCESS_ID: u32 = 0x3100_00F7;

pub const EMAIL_REP_RECEIVE_ALL_FAILURE_ID: u32 = 0x3100_00F8;

pub const EMAIL_REQ_PAGE_LIST_SIZE: usize = 1;

pub const EMAIL_REQ_DELETE_SIZE: usize = 40;

pub const EMAIL_REQ_SEND_SIZE: usize = 1_164;

pub const EMAIL_REQ_RECEIVE_ITEM_SIZE: usize = 16;

pub const EMAIL_REQ_RECEIVE_CASH_SIZE: usize = 8;

pub const EMAIL_REQ_RECEIVE_ALL_SIZE: usize = 8;

pub const EMAIL_REP_NEW_SIZE: usize = 4;

pub const EMAIL_REP_PAGE_LIST_SUCCESS_SIZE: usize = 1_024;

pub const EMAIL_REP_PAGE_LIST_FAILURE_SIZE: usize = 8;

pub const EMAIL_REP_DELETE_SUCCESS_SIZE: usize = 40;

pub const EMAIL_REP_DELETE_FAILURE_SIZE: usize = 44;

pub const EMAIL_REP_SEND_SUCCESS_SIZE: usize = 76;

pub const EMAIL_REP_SEND_FAILURE_SIZE: usize = 12;

pub const EMAIL_REP_RECEIVE_ITEM_SUCCESS_SIZE: usize = 16;

pub const EMAIL_REP_RECEIVE_ITEM_FAILURE_SIZE: usize = 20;

pub const EMAIL_REP_RECEIVE_CASH_SUCCESS_SIZE: usize = 12;

pub const EMAIL_REP_RECEIVE_CASH_FAILURE_SIZE: usize = 12;

pub const EMAIL_REP_RECEIVE_ALL_SUCCESS_SIZE: usize = 8;

pub const EMAIL_REP_RECEIVE_ALL_FAILURE_SIZE: usize = 12;

pub const EMAIL_UI_JEFFE_12_FONT_SIZE: f32 = 12.0;

pub const EMAIL_UI_JEFFE_14_FONT_SIZE: f32 = 12.0;

pub const EMAIL_UI_JEFFE_16_FONT_SIZE: f32 = 14.0;

pub const EMAIL_UI_JEFFE_06_FONT_SIZE: f32 = 7.0;

pub const EMAIL_UI_CHALET_SMALL_FONT_SIZE: f32 = 12.0;

pub const EMAIL_UI_LABEL_PADDING_TOP: f32 = 3.0;

pub const EMAIL_UI_LABEL_PADDING_BOTTOM: f32 = 3.0;

/// `Panel_NewEmail.DoText` moves only the postage caption down by three pixels.
pub const EMAIL_UI_POSTAGE_LABEL_Y_OFFSET: f32 = 3.0;

pub const EMAIL_UI_POSTAGE_LABEL_GAP: f32 = 5.0;

pub const EMAIL_UI_IMAGE_PATHS: [&str; 32] = [
    EMAIL_UI_FRAME_PATH,
    EMAIL_UI_LIST_PATH,
    EMAIL_UI_GUIDE_TAB_PATH,
    EMAIL_UI_GUIDE_TAB_HOVER_PATH,
    EMAIL_UI_PLAYER_TAB_PATH,
    EMAIL_UI_PLAYER_TAB_HOVER_PATH,
    EMAIL_UI_INACTIVE_TAB_FILL_PATH,
    EMAIL_UI_ATTACHMENT_PATH,
    EMAIL_UI_BUDDY_POPUP_PATH,
    EMAIL_UI_CALCULATOR_PAD_PATH,
    EMAIL_UI_CALCULATOR_POPUP_PATH,
    EMAIL_UI_DATA_BACK_PATH,
    EMAIL_UI_DATA_BOX_PATH,
    EMAIL_UI_SORT_ARROW_PATH,
    EMAIL_UI_TAROS_PATH,
    EMAIL_UI_PREVIOUS_PATH,
    EMAIL_UI_PREVIOUS_HOVER_PATH,
    EMAIL_UI_NEXT_PATH,
    EMAIL_UI_NEXT_HOVER_PATH,
    EMAIL_UI_COMPOSE_PATH,
    EMAIL_UI_LIST_SELECTION_PATH,
    EMAIL_UI_BUTTON_PATH,
    EMAIL_UI_BUTTON_HOVER_PATH,
    EMAIL_UI_RED_BUTTON_PATH,
    EMAIL_UI_RED_BUTTON_HOVER_PATH,
    EMAIL_UI_BACKDROP_PATH,
    EMAIL_UI_RIGHT_PANEL_PATH,
    EMAIL_UI_INVENTORY_PANEL_PATH,
    EMAIL_UI_SLOT_OCCUPIED_PATH,
    EMAIL_UI_SLOT_EMPTY_PATH,
    EMAIL_UI_CLOSE_PATH,
    EMAIL_UI_CLOSE_HOVER_PATH,
];

pub const EMAIL_UI_OPEN_SECONDS: f32 = 1.0;

pub const EMAIL_UI_RIGHT_OFFSCREEN_X: f32 = 1_020.0;

const _: [(); EMAIL_PAGE_SIZE] = [(); 5];

const _: [(); EMAIL_ATTACHMENT_COUNT] = [(); 4];

const _: [(); EMAIL_DELETE_BATCH_COUNT] = [(); 5];
