
pub const QUIT_MENU_BACKDROP_TEXTURE_PATH_ID: i64 = 535;

pub const QUIT_MENU_DIALOG_TEXTURE_PATH_ID: i64 = 47;

pub const QUIT_MENU_BUTTON_NORMAL_TEXTURE_PATH_ID: i64 = 449;

pub const QUIT_MENU_BUTTON_HOVER_TEXTURE_PATH_ID: i64 = 122;

pub const QUIT_MENU_CANCEL_NORMAL_TEXTURE_PATH_ID: i64 = 178;

pub const QUIT_MENU_CANCEL_HOVER_TEXTURE_PATH_ID: i64 = 640;
