use super::*;

pub const NATIVE_PLAYER_PREVIEW_CAMERA_ORDER: isize = GAMEPLAY_UI_CAMERA_ORDER + 1;

pub const NATIVE_PLAYER_CREATION_CAMERA_DISTANCE: f32 = 2.0;

pub const NATIVE_PLAYER_CREATION_CAMERA_HEIGHT: f32 = 0.7;

pub const NATIVE_PLAYER_CREATION_CAMERA_MIN_DISTANCE: f32 = 1.0;

pub const NATIVE_PLAYER_CREATION_CAMERA_MAX_DISTANCE: f32 = 3.0;
