
pub const GAMEPLAY_PLAYER_PORTRAIT_CAMERA_DISTANCE: f32 = 0.5;

pub const GAMEPLAY_PLAYER_PORTRAIT_CAMERA_HEIGHT: f32 = 0.2;

pub const GAMEPLAY_PLAYER_PORTRAIT_CAMERA_YAW_DEGREES: f32 = -20.0;

pub const GAMEPLAY_PLAYER_PORTRAIT_CAMERA_FOV_DEGREES: f32 = 45.0;

pub const GAMEPLAY_PLAYER_PORTRAIT_CAMERA_NEAR: f32 = 0.001;

pub const GAMEPLAY_PLAYER_PORTRAIT_CAMERA_FAR: f32 = 100.0;
