
pub(super) const TUTORIAL_INSTRUCTION_KEYS: &[(&str, &str)] = &[
    (
        "Move your mouse to the right and find the marker.",
        "tutorial.instruction.look_right",
    ),
    (
        "Move your mouse to the left and find the marker.",
        "tutorial.instruction.look_left",
    ),
    (
        "Push your mouse forward and find the marker.",
        "tutorial.instruction.look_up",
    ),
    (
        "Pull your mouse back and find the marker.",
        "tutorial.instruction.look_down",
    ),
    (
        "Press and hold the \"W\" key to move forward.",
        "tutorial.instruction.move_forward",
    ),
    (
        "Press the \"S\" key to move backwards.",
        "tutorial.instruction.move_backward",
    ),
    (
        "Press and hold the \"W\" key to move forward while steering with the mouse.",
        "tutorial.instruction.move_and_steer",
    ),
    (
        "Move to the marker near the ledge.",
        "tutorial.instruction.reach_ledge",
    ),
    (
        "Jump onto the ledge by pressing the Space Bar.",
        "tutorial.instruction.jump_to_ledge",
    ),
    (
        "Use your mouse to target a monster.",
        "tutorial.instruction.target_monster",
    ),
    (
        "Click the Left Mouse button to attack. Hold the button down for continuous fire.",
        "tutorial.instruction.attack_continuously",
    ),
    ("Defeat the monster.", "tutorial.instruction.defeat_monster"),
    ("Go to Numbuh Two.", "tutorial.instruction.go_to_numbuh_two"),
    (
        "Target Numbuh Two and click the Left Mouse button to talk.",
        "tutorial.instruction.target_numbuh_two",
    ),
    (
        "Select \"Transmitter Critters\" from mission menu.",
        "tutorial.instruction.select_transmitter_critters",
    ),
    (
        "Press \"Enter\" key to access the main menu. Then select \"Journal\".",
        "tutorial.instruction.open_journal",
    ),
    (
        "Click the \"Close\" button.",
        "tutorial.instruction.close_dialog",
    ),
    (
        "Talk to Buttercup.",
        "tutorial.instruction.talk_to_buttercup",
    ),
    (
        "Select \"A Fusion Matter\" from mission menu.",
        "tutorial.instruction.select_fusion_matter",
    ),
    (
        "Select the Dexbot attendant to use the warp gate.",
        "tutorial.instruction.select_dexbot_attendant",
    ),
    (
        "Click the \"Warp\" button to enter Fusion Buttercup's lair.",
        "tutorial.instruction.warp_into_fusion_lair",
    ),
    (
        "Go to the Fusion Portal.",
        "tutorial.instruction.go_to_fusion_portal",
    ),
    ("Talk to Dexter.", "tutorial.instruction.talk_to_dexter"),
    (
        "Use the warp gate to exit.",
        "tutorial.instruction.use_exit_warp_gate",
    ),
    (
        "Click the \"Warp\" button to exit the lair.",
        "tutorial.instruction.warp_out_of_lair",
    ),
    (
        "Select the tentacles to use the Fusion Portal.",
        "tutorial.instruction.select_portal_tentacles",
    ),
    (
        "Cross the bridge to escape.",
        "tutorial.instruction.cross_bridge",
    ),
    (
        "Press \"1\" to summon your Buttercup Nano.",
        "tutorial.instruction.summon_buttercup_nano",
    ),
    ("Stun the monster.", "tutorial.instruction.stun_monster"),
    (
        "Talk to Numbuh Two.",
        "tutorial.instruction.talk_to_numbuh_two",
    ),
];

pub(super) const REQUIRED_UI_KEYS: &[&str] = &[
    "ui.login.username",
    "ui.login.password",
    "ui.login.submit",
    "ui.login.connecting",
    "ui.login.discord",
    "ui.login.register",
    "ui.character_select.title",
    "ui.character_select.empty",
    "ui.character_select.unlimited_only",
    "ui.character_select.delete",
    "ui.character_select.create",
    "ui.character_select.enter",
    "ui.character_select.delete_prompt",
    "ui.character_select.level",
    "ui.common.quit",
    "ui.common.cancel",
    "ui.common.delete",
    "ui.common.continue",
    "ui.common.exit",
    "ui.common.or",
    "ui.character_create.title",
    "ui.character_create.random",
    "ui.character_create.step.body",
    "ui.character_create.boy",
    "ui.character_create.girl",
    "ui.character_create.skin",
    "ui.character_create.step.features",
    "ui.character_create.hair_variant",
    "ui.character_create.face_label",
    "ui.character_create.face_variant",
    "ui.character_create.eye_color",
    "ui.character_create.step.clothes",
    "ui.character_create.generate_name",
    "ui.character_create.custom_name",
    "ui.character_create.generated_name_rules",
    "ui.character_create.custom_name_question",
    "ui.character_create.custom_name_help",
    "ui.character_create.custom_name_rules",
    "ui.character_create.height.shortest",
    "ui.character_create.height.short",
    "ui.character_create.height.medium",
    "ui.character_create.height.tall",
    "ui.character_create.height.tallest",
    "ui.character_create.body.heavy",
    "ui.character_create.body.medium",
    "ui.character_create.body.light",
    "ui.character_create.name.blank_option",
    "ui.content.passthrough",
    "ui.hud.chat.open_hint",
    "ui.hud.chat.send",
    "ui.hud.chat.channel.all",
    "ui.hud.chat.channel.group",
    "ui.hud.chat.channel.buddy",
    "ui.hud.chat.message.local",
    "ui.hud.chat.message.group",
    "ui.hud.chat.message.buddy",
    "ui.hud.chat.message.direct",
    "ui.hud.chat.gamemaster_message",
    "ui.chat.command.speed.usage",
    "ui.chat.command.speed.denied",
    "ui.chat.command.speed.requested",
    "ui.chat.command.speed.failed",
    "ui.chat.command.speed.applied",
    "ui.chat.command.speed.controller_missing",
    "tutorial.chat.intro.buttercup",
    "tutorial.chat.intro.numbuh_five",
    "tutorial.chat.intro.ben",
    "tutorial.chat.intro.computress",
    "tutorial.chat.computress_instruction",
    "tutorial.instruction.look_right",
    "tutorial.instruction.look_left",
    "tutorial.instruction.look_up",
    "tutorial.instruction.look_down",
    "tutorial.instruction.move_forward",
    "tutorial.instruction.move_backward",
    "tutorial.instruction.move_and_steer",
    "tutorial.instruction.reach_ledge",
    "tutorial.instruction.jump_to_ledge",
    "tutorial.instruction.target_monster",
    "tutorial.instruction.attack_continuously",
    "tutorial.instruction.defeat_monster",
    "tutorial.instruction.go_to_numbuh_two",
    "tutorial.instruction.target_numbuh_two",
    "tutorial.instruction.select_transmitter_critters",
    "tutorial.instruction.open_journal",
    "tutorial.instruction.close_dialog",
    "tutorial.instruction.talk_to_buttercup",
    "tutorial.instruction.select_fusion_matter",
    "tutorial.instruction.select_dexbot_attendant",
    "tutorial.instruction.warp_into_fusion_lair",
    "tutorial.instruction.go_to_fusion_portal",
    "tutorial.instruction.talk_to_dexter",
    "tutorial.instruction.use_exit_warp_gate",
    "tutorial.instruction.warp_out_of_lair",
    "tutorial.instruction.select_portal_tentacles",
    "tutorial.instruction.cross_bridge",
    "tutorial.instruction.summon_buttercup_nano",
    "tutorial.instruction.stun_monster",
    "tutorial.instruction.talk_to_numbuh_two",
    "ui.mission.journal.current",
    "ui.tutorial.cutscene.time_jump_error",
    "status.login.credentials",
    "status.login.username",
    "status.login.password",
    "status.login.network_error",
    "status.login.failed",
    "status.login.disconnected",
    "status.login.disconnected_error",
    "status.login.offline_error",
    "status.connecting",
    "status.message",
    "status.character_select.subscription_only",
    "status.character_select.no_available_slot",
    "status.character_select.no_selectable_character",
    "status.character_select.create_pending",
    "status.character_select.delete_pending",
];
