use super::*;

#[derive(Resource, Default)]
pub(super) struct PreviewState {
    pub(super) frames: u32,
    pub(super) ready_frame: Option<u32>,
    pub(super) initial_spine_rotation: Option<Quat>,
    pub(super) last_run_seek_time: Option<f32>,
    pub(super) last_run_motion_frame: Option<u32>,
    pub(super) max_frozen_run_frames: u32,
    pub(super) motion_observed: bool,
    pub(super) pause_injected: bool,
    pub(super) pause_recovered: bool,
    pub(super) stop_injected_frame: Option<u32>,
    pub(super) stop_recovered: bool,
    pub(super) attack_pending: bool,
    pub(super) attack_key_down: bool,
    pub(super) attack_dispatched: bool,
    pub(super) staying_queued: bool,
    pub(super) standup_queued: bool,
    pub(super) standup_seen: bool,
    pub(super) standup_node: Option<AnimationNodeIndex>,
    pub(super) standup_last_seek_time: f32,
    pub(super) startup_landing_grounded: bool,
    pub(super) jumpend_seen: bool,
    pub(super) jumpend_node: Option<AnimationNodeIndex>,
    pub(super) jumpend_last_seek_time: f32,
    pub(super) stand1_return_frame: Option<u32>,
    pub(super) capture_issued: bool,
    pub(super) capture_saved: bool,
    pub(super) dismount_frame: Option<u32>,
    pub(super) dismount_capture_issued: bool,
    pub(super) dismount_capture_saved: bool,
    pub(super) weapon_stage: u8,
    pub(super) weapon_step_frame: u32,
    pub(super) emote_cycles: u32,
    pub(super) emote_started: bool,
    pub(super) emote_interrupt_frame: Option<u32>,
    pub(super) emote_echo: Option<(i32, u32)>,
    pub(super) emote_attack_seen: bool,
}
